# Generated by Django 5.0.6 on 2024-07-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishLiked', to='network.publish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLiked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
