# Generated by Django 5.0.6 on 2024-07-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_wacthlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wacthlist',
            new_name='Watchlist',
        ),
    ]
