# Generated by Django 5.0.6 on 2024-07-13 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='auction_title',
            field=models.CharField(default='No Winner Yet', max_length=64),
        ),
        migrations.AlterField(
            model_name='winners',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='auctions.auctions'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
